### ISSUE TITLE
Edges over screen are lost/ overscan/ no menu

### ISSUE THREAD

**Issue by kyle775** [philplckthun/PiTV#10]
I cannot see the edges of the screen just red screen with "goto 192.168.1.69" in the center.

**Comment by philplckthun** [comment]
This is not a bug. This is expected behaviour.

I don't really understand your issue with this. The Pi is supposed to show this fullscreen, as it is the host connected to the TV.

**Comment by kyle775** [comment]
Boy, I feel quite silly.  I was under the impression I used keyboard and mouse connected to the pi, when in fact I should use my mobile phone.  I might suggest adding something to that message "Using your mobile device or another remote goto <ip>.
Sorry for not understanding to begin with.  Thanks!
