### ISSUE TITLE
Series episode plays at 2.00 speed automatically.

### ISSUE THREAD

**Issue by kyle775** [philplckthun/PiTV#11]
Episode will play very fast.
1. Boot the pi
2. Filter series
3. Select series, select season, select episode
4. Select play at 480p
5. Episode begins playing at 2.00 speed.

**Comment by philplckthun** [comment]
Have you accidentally pressed a key that increases OMXPlayer's playback speed? OMXPLayer will preserve this setting, even if you restart it.

Check out this page for its shortcuts for changing the playback speed to default: http://elinux.org/Omxplayer

**Comment by kyle775** [comment]
Thanks you very much.
It seems like none of these keyboard shortcuts work until after I stop
playback from my remote device.
