### ISSUE TITLE
Cannot see cursor at all times

### ISSUE THREAD

**Issue by kyle775** [philplckthun/PiTV#9]
My cursor/mouse does no display, only at times when I move it quickly.  Although I can use it for example if I notice that hovering over a link changes and I click it will follow the link or click the button, but I cannot see the cursor.

**Comment by philplckthun** [comment]
This is not a bug as well. This seems to be an issue with your browser / the device you use as a remote. Here too, I'm not really sure, what you mean, as the CSS doesn't hide the cursor anywhere.
